[project]
name = "job-raptor"
version = "0.1.0"
description = "Job Raptor is a job search assistant for LinkedIn."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.6",
    "python-jobspy>=1.1.80",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
